/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Stdout {
  EnterAlternateScreen = 0,
  LeaveAlternateScreen = 1
}
export type JSFrame = Frame
export class Frame {
  constructor()
  renderWidget(paragraph: JSParagraph, area: JSRect): void
  size(): JSRect
}
export type JSParagraph = Paragraph
export class Paragraph {
  text: string
  constructor(text: string)
}
export type JSRect = JsRect
export class JsRect { }
export type InnerTerminal = Terminal
export class Terminal {
  constructor()
  /**
   * # Safety
   * asjklddsjlk
   */
  draw(callback: (frame: Frame) => void): Promise<void>
  setup(state: Stdout): void
  restore(state: Stdout): void
}
